// module
import type { Metadata } from 'next'
import 'react-toastify/dist/ReactToastify.css';
// custom
import MainLayout from '@/components/main-layout'

export const metadata: Metadata = {
  title: 'Bime Bazar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir='rtl'>
      <MainLayout>
        {children}
      </MainLayout>
    </html>
  )
}
